In [89]:
import numpy as np

x_values = np.random.uniform(0, 1.0, size = (100, 100))
x_values[0, :]

array([  1.70263007e-01,   9.46986120e-01,   9.89577348e-01,
         7.26733198e-01,   3.16498620e-01,   4.42232818e-01,
         4.10217561e-01,   1.64643824e-01,   8.37599568e-01,
         2.10147902e-01,   1.30010261e-01,   8.01465933e-03,
         2.84911622e-01,   8.79462928e-01,   2.04631240e-01,
         2.68946367e-01,   2.87745125e-02,   4.31485290e-01,
         9.06333639e-01,   3.33421741e-01,   3.76234322e-01,
         7.40781442e-01,   8.23760496e-01,   6.75325195e-03,
         2.10750370e-01,   2.13114213e-01,   6.48670682e-01,
         3.79568180e-01,   4.79532926e-01,   9.62336967e-01,
         4.25368995e-01,   6.18741197e-01,   8.01003392e-01,
         7.05202828e-01,   5.03272532e-01,   4.21017261e-01,
         7.80614045e-01,   7.74541730e-02,   6.57127004e-01,
         2.80893502e-01,   3.48215196e-01,   8.84068756e-01,
         2.16604098e-01,   4.80754573e-01,   2.38859850e-01,
         2.51300263e-01,   6.41001178e-01,   8.50439086e-01,
         9.73603535e-02,

In [94]:
THETAS = 2 ** np.random.uniform(-4, 4, size = 100)
print(THETAS)

y_values = THETAS.dot(x_values)
print(y_values.shape)
noises = np.random.normal(scale = 1.0, size = 100)
y_values += noises

[  5.74574054   4.82422001   0.53860842   0.41146175   2.31936824
   5.47963782   0.13547114   0.22953736  10.23752646   3.18715272
   0.19665087   1.18660335   0.09538552   0.17406226   0.48105072
   0.14367187   0.58810015   0.48050413   0.2659979    0.34457091
   0.13098494   5.61336873   1.67648365  15.25383852   2.79170438
   7.1927544    0.48167103   0.07630191   9.30972495   0.25470224
   0.72382738   6.03537376   0.31071429   2.93786874   2.20090459
   0.22590479   0.13314344   8.02799458   0.84378561   0.1255403
   0.3178777    0.24414409   0.39191525   4.85621447   0.10654584
   0.37236342   4.86886106   0.81758248   0.17149922  11.94646419
   4.12077941   0.08968385   0.37850987   1.15769705   0.09913275
   0.1887891    1.38800159  13.37175723   0.31727725   0.08235317
   0.09500269   3.07058611   0.55809421   0.07500696   0.06940712
   0.0965854    0.07824773   0.44010141   7.27369598   5.54023802
  12.6406731    1.07850787   0.28348365   7.69945947   0.24014311
   5.449274

In [95]:
def sse(x_values, y_values, thetas):
    yhat_values = thetas.dot(x_values)
    errors = y_values - yhat_values
    squared_errors = errors * errors
    return np.sum(squared_errors)

def rmse(x_values, y_values, thetas):
    return np.sqrt(
        sse(x_values, y_values, thetas) / x_values.shape[0]
    )

print(
    sse(x_values, y_values, THETAS)
)
print(
    rmse(x_values, y_values, THETAS)
)

111.258931211
1.05479349264


In [96]:
DELTA = 0.0025

def update_thetas(x_values, y_values, thetas):
    current_sse = sse(x_values, y_values, thetas)
    
    new_thetas = np.copy(thetas)

    for idx in range(len(new_thetas)):
        tweaked_thetas = np.copy(thetas)
        tweaked_thetas[idx] += DELTA
        tweaked_sse = sse(x_values, y_values, tweaked_thetas)
        if tweaked_sse < current_sse:
            new_thetas[idx] += DELTA
        else:
            new_thetas[idx] -= DELTA

    return new_thetas

update_thetas(x_values, y_values, np.zeros(shape = THETAS.shape))

array([ 0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,  0.0025,
        0.0025,  0.0

In [97]:
def run_optimization(x_values, y_values, thetas):
    for step_idx in range(10000):
        thetas = update_thetas(x_values, y_values, thetas)
        current_rmse = rmse(x_values, y_values, thetas)

        if step_idx % 1000 == 0:
            print(f"{step_idx}: {current_rmse:0.2f}")
        
    return thetas

run_optimization(x_values, y_values, np.zeros(THETAS.shape))

0: 124.67
1000: 10.55
2000: 4.47
3000: 1.85
4000: 1.54
5000: 1.54
6000: 1.54


KeyboardInterrupt: 

In [98]:
def partials(x_values, y_values, thetas):
    yhat = thetas.dot(x_values)
    errors = y_values - yhat
    return 2 * np.sum(
        errors.reshape((1, x_values.shape[0])) * -x_values,
        axis = 1
    )

LEARNING_RATE = 0.00025
def gd_update_thetas(x_values, y_values, thetas):
    return thetas - LEARNING_RATE * partials(x_values, y_values, thetas)

def run_gd_optimization(x_values, y_values, thetas):
    for step_idx in range(10000):
        thetas = gd_update_thetas(x_values, y_values, thetas)
        current_rmse = rmse(x_values, y_values, thetas)

        if step_idx % 1000 == 0 :
            print(f"{step_idx}: {current_rmse:0.2f}")
        
    return thetas

print(
    rmse(x_values, y_values, np.zeros(THETAS.shape))
)
run_gd_optimization(x_values, y_values, np.zeros(THETAS.shape))

124.790012657
0: 34.23
1000: 1.16
2000: 0.71
3000: 0.52
4000: 0.42
5000: 0.36
6000: 0.31
7000: 0.28
8000: 0.25
9000: 0.23


array([  5.88754232e+00,   5.17182816e+00,   1.49806497e-02,
        -2.22879697e+00,   2.15876198e+00,   3.54598950e+00,
         8.51556917e-01,   9.98543108e-01,   1.07788407e+01,
         2.69896272e+00,   2.09888342e+00,   1.05842067e+00,
         2.90165932e-01,  -4.47627960e-01,   1.88252186e+00,
         1.67158643e+00,  -5.44916978e-01,   1.17178674e+00,
         1.07725930e+00,  -1.34419948e+00,  -4.16999459e-01,
         5.56603480e+00,   9.02652363e-01,   1.51541536e+01,
         3.35004479e+00,   8.34982993e+00,  -1.78137344e-01,
         1.47863824e-01,   8.98117487e+00,   1.32292773e+00,
         2.24715924e+00,   6.55621048e+00,  -1.74029465e-01,
         3.69854418e+00,   3.39813731e+00,   8.83934609e-01,
        -6.48230234e-01,   8.07909981e+00,   4.59600380e-01,
         4.23115025e-01,   3.39245321e-01,   1.89031478e-01,
        -5.89765977e-01,   3.11034613e+00,   6.83215015e-01,
         1.91688439e-02,   4.42244699e+00,   2.17684640e+00,
         6.58174211e-01,